name: default

channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip=21.3.1
  - ipykernel=6.7.0
  - pip:
      - "-e git+https://github.com/scaleoutsystems/fedn.git@feature/gramine-compatibility#egg=fedn&subdirectory=fedn"
      - fire==0.3.1
      - autopep8==1.6.0
      - meson>=0.55
      - toml>=0.10
      - protobuf==3.19.4
      - ninja==1.10.0
      - clang-format==13.0.0
